[package]
name = "fast_scripting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
lazy_static = "1.4.0"
pest = "2.7.10"
pest_derive = "2.7.10"